import type { CaseInput } from "@/lib/types";

export const sampleCaseInput: CaseInput = {
  diagnosis: "Рак молочной железы, трижды негативный подтип",
  stage: "4",
  stage_numeric: 4,
  stage_raw: "IV",
  sex: "female",
  age: 54,
  weight_kg: 68,
  height_cm: 168,
  bsa_m2: 1.78,
  ecog: 1,
  histology: "Инвазивная карцинома молочной железы",
  allergies: [],
  biomarkers: ["ER 0", "PR 0", "HER2 negative", "PD-L1 CPS 10"],
  icd10_code: "C50.9",
  icd10_name_ru: "Злокачественное новообразование молочной железы неуточненной локализации",
  nosology_label_ru: "Злокачественное новообразование молочной железы",
  primary_localization: "Молочная железа",
  tnm: "cT2N1M1",
  her2_status: "negative",
  pd_l1_cps: 10,
  msi_mmr: "MSS",
  comorbidities: ["Артериальная гипертензия"],
  prior_surgeries: ["Секторальная резекция молочной железы"],
  radiation_history: [],
  labs: {
    "Hb": "121 г/л",
    "ALT": "26 Ед/л",
  },
  neutrophils_abs: 3.2,
  platelets: 220,
  hemoglobin: 121,
  bilirubin_total: 14,
  alt: 26,
  ast: 24,
  creatinine: 79,
  albumin: 42,
  inr: 1,
  disease_status: "прогрессирование",
  metastases: ["печень"],
  last_imaging_date: "2025-02-20",
  complications: [],
  treatment_history: [
    {
      line: 1,
      regimen: "Паклитаксел + Карбоплатин",
      start_date: "2021-09-01",
      end_date: "2022-03-10",
      best_response: "стабилизация",
      stop_reason: "прогрессирование",
    },
  ],
  contraindications: [],
  treatment_goal: "паллиативное лечение",
  regimen_protocol: "ПХТ паклитаксел + карбоплатин",
  protocol_assignment_date: "2025-03-10",
  planned_therapy_line: 2,
  planned_drugs: [
    {
      name: "Паклитаксел",
      dose_value: 80,
      dose_unit: "мг/м²",
      route: "в/в",
      schedule_days: "1,8,15",
      cycle_days: 28,
    },
    {
      name: "Карбоплатин",
      dose_value: 5,
      dose_unit: "AUC",
      route: "в/в",
      schedule_days: "1",
      cycle_days: 21,
    },
  ],
  as_of_date: "2025-03-10",
  current_plan: [
    "ПХТ паклитаксел + карбоплатин",
    "Контроль по ПЭТ-КТ",
    "Рассмотреть смену линии терапии при прогрессировании",
  ],
  timeline: [
    {
      event_date: "2021-09-01",
      event_type: "line_1_start",
      payload: {
        therapy: "Паклитаксел + Карбоплатин",
        intent: "systemic",
      },
    },
    {
      event_date: "2022-03-16",
      event_type: "progression",
      payload: {
        source: "ПЭТ-КТ",
        note: "Отрицательная динамика",
      },
    },
    {
      event_date: "2023-05-29",
      event_type: "tumor_board",
      payload: {
        recommendation: "Иксабепилон + капецитабин",
      },
    },
  ],
};
